language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - GH_REF=github.com/developmentseed/oc-map.git
  - DEPLOY_BRANCH=master
  - secure: ltQzBSdwba8dJXSVAll6IpczL5UNvhtoJ0Cake+oZX7mF53jprfHu68AuDwOvPiWCar3IMwoW/rinkOe60V4j/LQfjUc1q0dY0ziEUGXZkHmA/Gjm5GmZojQXepM3OLlRuHtQ+aOT0ByqgfXEsFxGLsdTlBrgezsupaD0+CEaazdWoyaA0U1bWRpbxBZ5NwnMgtjevpu6iocKIReVThDERlOsXKM2/Sb+/nsg4gu02GCMSr9QT755go2Uq8yhXDDMfT7EIr6pkRZDPSApYkQZbF6CAUYpg+VnRc2Kg381Ve7jsnYMnJ9as39iTtt5NPgEhzq812nEwdCh2X/Zdr8BbUtROYNKKNZqMMb6uqcY+Z/C86GrZqmzbsYqqj6xJ/Ozqxdipqy/Pk2qOuB3pkO1k0IRnKSwYAzD5k9jIXNX1ZJfAPTQ9hvB1B6z24N8WOmhArTqM+JhclheRrgQZ8joX+4Zp+Jn2BbauSqZz2GZ6u8BSl2zA7oDXNjNtdmhgUKAZpiGUeYW+URCtYD5qEu35uvu8oboW2kf8ruQJeJZGPXGlmRDHdMFN7LhjeNAf0FF/wYmLBEfYZiT4rr2VJJOadIDhXcW/JMGDw+YnKMDmrcKDF2meXGgUncnBB2cjd7CZAV1BQKW9eafkEd1Wq/erWandWWEIB3bLEEEdMBvkM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
